name: Sample Doppler Secrets Access
on: [push]

jobs:
    main:
        runs-on: ubuntu-latest # ubuntu, macos, and windows are supported
        steps:
            - name: Install Doppler CLI
              uses: dopplerhq/cli-action@v1

            - name: Pass all secrets to next steps
              run: doppler secrets download --no-file --format env-no-quotes >> $GITHUB_ENV; 
              env:
                DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_DEV }}
                
            - name: Print variable from Doppler 
              run: echo "$DOPPLER_SECRET_1"
              
            - name: Print all secrets raw
              run: doppler secrets --raw
              env:
                DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_DEV }}
